# Mechanistic in Silico Simulation Results Notebook

## Instructions

[Comprehensive documentation here](Docs/simglucose.md) detailing how to run Trio oref algorithm variants through simglucose to conduct mechanistic in silico simulations.

### Run One Virtual Person

```
python3 simglucose/run_sim.py -u <virtual_patient> -a <alg_name> -d <days> -scen <meal_scenario_path> -fn <results_file>
```
* `virtual_patient`: Name of virtual patient. Valid patient names are age group followed by three digits. Age groups = [child, adolescent, adult]. Valid digits = [001, 002, 003, 004, 005, 006, 007, 008, 009, 010]
    * eg. adolescent002 or adult010
* `alg_name`: Optional argument. Name of the Javascript oref algorithm variant to run instead of the Swift algorithm. Defaults to `"swift"` if no argument given. Possible choices:
    * `jsbug`: Original Javascript implementation.
    * `js`: Javascript implementation of bug-free Swift oref algorithm.
    * `swift`: Swift implementation of oref algorithm.
* `days`: Number of days simulation runs (must be whole number)
* `meal_scenario_path`: Optional argument. Filepath to precomputed .npy file containing meal scenario.
* `results_file`: Filepath to csv file where outputs will be written to.

### Run All Virtual People
Run the following commands to execute this [script](./Scripts/run_simglucose.sh) which simulates all 30 virtual persons. There is the option to run simulations in parallel in independent processes. Set `PARALLELISM` to the number of processes you want to run concurrently. 

```shell
chmod +x Scripts/run_simglucose.sh # if have not run script yet
./Scripts/run_simglucose.sh
```

## Glucose Metric Analysis

In [4]:
import numpy as np
import pandas as pd
from typing import Literal

In [7]:
def patient_names(age: Literal["adult", "adolescent", "child"]):
    code_names = [f"{age}{n}" for n in ["001","002","003","004","005","006","007","008","009","010"]]
    age_cap = f"{age[0].upper()}{age[1:]}"
    display_names = [f"{age_cap} {n}" for n in range(1,11)]
    return code_names, display_names

In [13]:
children, children_display = patient_names("child")
adolescents, adolescents_display = patient_names("adolescent")
adults, adults_display = patient_names("adult")
all_users = children + adolescents + adults
all_users_display = children_display + adolescents_display + adults_display
results_folder = "simglucoseResults"

In [14]:
def glycemia_risk_index(tar, tbr, tvar, tvbr):
    gri = 3 * tvbr + 2.4 * tbr + 1.6 * tvar + 0.8 * tar
    return 100.0 if gri > 100.0 else gri

def glucose_stats(glucose):
    low_bound = 70
    v_low_bound = 54
    v_high_bound = 250
    high_bound = 180
    glucose = np.array(glucose)

    tar = 100 * np.average(glucose > high_bound)
    tvar = 100 * np.average(glucose > v_high_bound)
    tbr = 100 * np.average(glucose < low_bound)
    tvbr = 100 * np.average(glucose < v_low_bound)
    tir = 100 - tar - tbr

    gri = glycemia_risk_index(tar, tbr, tvar, tvbr)

    return tir, tar, tbr, tvar, tvbr, gri

In [44]:
def user_results(user:str, alg:str):
    path = f"{results_folder}/{user}/{alg}.csv"
    glucose = pd.read_csv(path)['CGM'].to_list()
    return glucose_stats(glucose)

def table_round(n, pct:bool):
    end = '%' if pct else ''
    return f"{round(n, 1)}{end}"
    
def age_group_results(group:list, user_display:list, alg:str):
    results = {"User":[], "TIR":[], "TAR":[], "TBR":[], "TVAR":[], 
                    "TVBR":[], "GRI":[]}
    raw_results = {"TIR":[], "TAR":[], "TBR":[], "TVAR":[], "TVBR":[], "GRI":[]}
    
    for i in range(len(group)):
        tir, tar, tbr, tvar, tvbr, gri = user_results(group[i], alg)
        results["User"].append(user_display[i])
        results["TIR"].append(table_round(tir, True))
        raw_results["TIR"].append(tir)
        results["TAR"].append(table_round(tar, True))
        raw_results["TAR"].append(tar)
        results["TBR"].append(table_round(tbr, True))
        raw_results["TBR"].append(tbr)
        results["TVAR"].append(table_round(tvar, True))
        raw_results["TVAR"].append(tvar)
        results["TVBR"].append(table_round(tvbr, True))
        raw_results["TVBR"].append(tvbr)
        results["GRI"].append(table_round(gri, False))
        raw_results["GRI"].append(gri)

    for category in results.keys():
        if category == "User": 
            results["User"].append("Mean")
            results["User"].append("Standard Deviation")
        else:
            avg = np.average(raw_results[category]).item()
            sd = np.std(raw_results[category]).item()
            show_pct = category != "GRI"
            results[category].extend([table_round(avg, show_pct), table_round(sd, show_pct)])

    return results

In [45]:
print('Trio Swift Implemention Simulation Results on Children')
df = pd.DataFrame.from_dict(age_group_results(children, children_display, 'swift'))
display(df.style.hide())

print('Trio Javascript Implemention Simulation Results on Children')
df = pd.DataFrame.from_dict(age_group_results(children, children_display, 'jsbug'))
display(df.style.hide())

Trio Swift Implemention Simulation Results on Children

Trio Javascript Implemention Simulation Results on Children

In [46]:
print('Trio Swift Implemention Simulation Results on Adolescents')
df = pd.DataFrame.from_dict(age_group_results(adolescents, adolescents_display, 'swift'))
display(df.style.hide())

print('Trio Javascript Implemention Simulation Results on Adolescents')
df = pd.DataFrame.from_dict(age_group_results(adolescents, adolescents_display, 'jsbug'))
display(df.style.hide())

Trio Swift Implemention Simulation Results on Adolescents

Trio Javascript Implemention Simulation Results on Adolescents

In [47]:
print('Trio Swift Implemention Simulation Results on Adults')
df = pd.DataFrame.from_dict(age_group_results(adults, adults_display, 'swift'))
display(df.style.hide())

print('Trio Javascript Implemention Simulation Results on Adults')
df = pd.DataFrame.from_dict(age_group_results(adults, adults_display, 'jsbug'))
display(df.style.hide())

Trio Swift Implemention Simulation Results on Adults

Trio Javascript Implemention Simulation Results on Adults

In [70]:
print('Trio Swift Implemention Simulation Per User Results')
df = pd.DataFrame.from_dict(age_group_results(all_users, all_users_display, 'swift'))
display(df.style.hide())


print('Trio Javascript Implemention Simulation Per User Results')
df = pd.DataFrame.from_dict(age_group_results(all_users, all_users_display, 'jsbug'))
display(df.style.hide())

Trio Swift Implemention Simulation Per User Results

Trio Javascript Implemention Simulation Per User Results

## Parkes Error Analysis

In [49]:
from ParkesErrorGrid.parkes_error import ParkesError

In [50]:
def user_parkes_grid(user, user_display=None, gen_plot=False):

    if gen_plot and not user_display:
        raise Exception(f"Must give value for user_display if gen_plot=True.")
    
    ref_trace = pd.read_csv(f"simglucoseResults/{user}/swift.csv")["CGM"].to_list()
    pred_trace = pd.read_csv(f"simglucoseResults/{user}/jsbug.csv")["CGM"].to_list()
    grid = ParkesError(ref_trace, pred_trace)
    if gen_plot:
        grid.plot(user_display, "Swift Algorithm Glucose", 
                "Original Javascript Algorithm Glucose", size=1, 
                save_fig_path=f"simglucoseResults/{user}/parkes_error.png")
        
    grid_flip = ParkesError(pred_trace, ref_trace)
    if gen_plot:
        grid_flip.plot(user_display, "Original Javascript Algorithm Glucose",
                "Swift Algorithm Glucose", size=1, 
                save_fig_path=f"simglucoseResults/{user}/parkes_error_flipped.png")

    return grid.zone_count(), grid_flip.zone_count()

In [64]:
swift_ref_users = {}
js_ref_users = {}

for user, user_display in zip(all_users, all_users_display):
    swift_ref, js_ref = user_parkes_grid(user)
    n = sum(swift_ref.values())
    swift_ref_users[user_display] = [table_round(100*count/n, True) for count in swift_ref.values()]
    js_ref_users[user_display] = [table_round(100*count/n, True) for count in js_ref.values()]

In [65]:
cols = ['Zone A', 'Zone B', 'Zone C', 'Zone D', 'Zone E']

print("Parkes error analysis results with Swift implementation being reference algorithm.")
df = pd.DataFrame.from_dict(swift_ref_users, orient='index', columns=cols)
display(df)

Parkes error analysis results with Swift implementation being reference algorithm.

               Zone A Zone B Zone C Zone D Zone E
Child 1         97.6%   2.4%   0.0%   0.0%   0.0%
Child 2        100.0%   0.0%   0.0%   0.0%   0.0%
Child 3        100.0%   0.0%   0.0%   0.0%   0.0%
Child 4         92.0%   7.8%   0.2%   0.0%   0.0%
Child 5         99.8%   0.2%   0.0%   0.0%   0.0%
Child 6        100.0%   0.0%   0.0%   0.0%   0.0%
Child 7        100.0%   0.0%   0.0%   0.0%   0.0%
Child 8         99.9%   0.1%   0.0%   0.0%   0.0%
Child 9         99.4%   0.6%   0.0%   0.0%   0.0%
Child 10        99.9%   0.1%   0.0%   0.0%   0.0%
Adolescent 1   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 2   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 3   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 4   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 5   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 6   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 7   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 8   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 9   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 10  100.0%   0.0%   0.0%   0.0%   0.0%
Adult 1        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 2        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 3        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 4        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 5        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 6        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 7         99.7%   0.3%   0.0%   0.0%   0.0%
Adult 8        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 9        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 10       100.0%   0.0%   0.0%   0.0%   0.0%

In [66]:
print("Parkes error analysis results with Javascript implementation being reference algorithm.")
df = pd.DataFrame.from_dict(js_ref_users, orient='index', columns=cols)
display(df)

Parkes error analysis results with Javascript implementation being reference algorithm.

               Zone A Zone B Zone C Zone D Zone E
Child 1         98.9%   1.1%   0.0%   0.0%   0.0%
Child 2        100.0%   0.0%   0.0%   0.0%   0.0%
Child 3         99.9%   0.1%   0.0%   0.0%   0.0%
Child 4         92.6%   7.4%   0.0%   0.0%   0.0%
Child 5        100.0%   0.0%   0.0%   0.0%   0.0%
Child 6        100.0%   0.0%   0.0%   0.0%   0.0%
Child 7        100.0%   0.0%   0.0%   0.0%   0.0%
Child 8         99.8%   0.2%   0.0%   0.0%   0.0%
Child 9         99.5%   0.5%   0.0%   0.0%   0.0%
Child 10       100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 1   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 2   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 3   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 4   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 5   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 6   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 7   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 8   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 9   100.0%   0.0%   0.0%   0.0%   0.0%
Adolescent 10  100.0%   0.0%   0.0%   0.0%   0.0%
Adult 1        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 2        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 3        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 4        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 5        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 6        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 7        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 8        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 9        100.0%   0.0%   0.0%   0.0%   0.0%
Adult 10       100.0%   0.0%   0.0%   0.0%   0.0%