# Simglucose Simulation Results Notebook

## Instructions

[Comprehensive documentation here](Docs/simglucose.md) detailing how to run Trio oref algorithm variants through simglucose to conduct mechanistic in silico simulations.

### Run One Virtual Person

```
python3 simglucose/run_sim.py -u <virtual_patient> -a <alg_name> -d <days> -scen <meal_scenario_path> -fn <results_file>
```
* `virtual_patient`: Name of virtual patient. Valid patient names are age group followed by three digits. Age groups = [child, adolescent, adult]. Valid digits = [001, 002, 003, 004, 005, 006, 007, 008, 009, 010]
    * eg. adolescent002 or adult010
* `alg_name`: Optional argument. Name of the Javascript oref algorithm variant to run instead of the Swift algorithm. Defaults to `"swift"` if no argument given. Possible choices:
    * `jsbug`: Original Javascript implementation.
    * `js`: Javascript implementation of bug-free Swift oref algorithm.
    * `swift`: Swift implementation of oref algorithm.
* `days`: Number of days simulation runs (must be whole number)
* `meal_scenario_path`: Optional argument. Filepath to precomputed .npy file containing meal scenario.
* `results_file`: Filepath to csv file where outputs will be written to.

### Run All Virtual People
Run the following commands to execute this [script](./Scripts/run_simglucose.sh) which simulates all 30 virtual persons. There is the option to run simulations in parallel in independent processes. Set `PARALLELISM` to the number of processes you want to run concurrently. 

```shell
chmod +x Scripts/run_simglucose.sh # if have not run script yet
./Scripts/run_simglucose.sh
```

## Code

In [1]:
import numpy as np
import pandas as pd

In [2]:
children = [f"child{n}" for n in ["001","002","003","004","005","006","007","008","009","010"]]
children_display = [f"child {n}" for n in range(1, 11)]
adolescents = [f"adolescent{n}" for n in ["001","002","003","004","005","006","007","008","009","010"]]
adolescents_display = [f"adolescent {n}" for n in range(1, 11)]
adults = [f"adult{n}" for n in ["001","002","003","004","005","006","007","008","009","010"]]
adults_display = [f"adult {n}" for n in range(1, 11)]
all_users = children + adolescents + adults
all_users_display = children_display + adolescents_display + adults_display

results_folder = "simglucoseResults"

In [3]:
def glycemia_risk_index(tar, tbr, tvar, tvbr):
    gri = 3 * tvbr + 2.4 * tbr + 1.6 * tvar + 0.8 * tar
    return 100.0 if gri > 100.0 else gri

def glucose_stats(glucose):
    low_bound = 70
    v_low_bound = 54
    v_high_bound = 250
    high_bound = 180
    glucose = np.array(glucose)

    tar = 100 * np.average(glucose > high_bound)
    tvar = 100 * np.average(glucose > v_high_bound)
    tbr = 100 * np.average(glucose < low_bound)
    tvbr = 100 * np.average(glucose < v_low_bound)
    tir = 100 - tar - tbr

    gri = glycemia_risk_index(tar, tbr, tvar, tvbr)

    return tir, tar, tbr, tvar, tvbr, gri

In [4]:
def user_results(user:str, alg:str):
    path = f"{results_folder}/{user}/{alg}.csv"
    glucose = pd.read_csv(path)['CGM'].to_list()
    return glucose_stats(glucose)

def age_group_results(group:list, user_display:list, alg:str):
    results = {"User":[], "TIR":[], "TAR":[], "TBR":[], "TVAR":[], 
                     "TVBR":[], "GRI":[]}
    
    for i in range(len(group)):
        tir, tar, tbr, tvar, tvbr, gri = user_results(group[i], alg)
        results["User"].append(user_display[i])
        results["TIR"].append(tir)
        results["TAR"].append(tar)
        results["TBR"].append(tbr)
        results["TVAR"].append(tvar)
        results["TVBR"].append(tvbr)
        results["GRI"].append(gri)

    for category, values in results.items():
        if category == "User": 
            results["User"].append("average")
            results["User"].append("standard deviation")
        else:
            avg = np.average(results[category]).item()
            sd = np.std(results[category]).item()
            results[category].extend([avg, sd])

    return results

In [5]:
print('Children Swift oref Simulation Results')
df = pd.DataFrame.from_dict(age_group_results(children, children_display, 'swift'))
display(df.style.hide())

print('Children Buggy Javascript oref Simlation Results')
df = pd.DataFrame.from_dict(age_group_results(children, children_display, 'jsbug'))
display(df.style.hide())

Children Swift oref Simulation Results

Children Buggy Javascript oref Simlation Results

In [6]:
print('Adolescent Swift oref Simulation Results')
df = pd.DataFrame.from_dict(age_group_results(adolescents, adolescents_display, 'swift'))
display(df.style.hide())

print('Adolescent Buggy Javascript oref Simulation Results')
df = pd.DataFrame.from_dict(age_group_results(adolescents, adolescents_display, 'jsbug'))
display(df.style.hide())

Adolescent Swift oref Simulation Results

Adolescent Buggy Javascript oref Simulation Results

In [7]:
print('Adult Swift oref Simulation Results')
df = pd.DataFrame.from_dict(age_group_results(adults, adults_display, 'swift'))
display(df.style.hide())

print('Adult Buggy Javascript oref Simulation Results')
df = pd.DataFrame.from_dict(age_group_results(adults, adults_display, 'jsbug'))
display(df.style.hide())

Adult Swift oref Simulation Results

Adult Buggy Javascript oref Simulation Results

In [8]:
print('All Virtual Persons Swift oref Simulation Results')
df = pd.DataFrame.from_dict(age_group_results(all_users, all_users_display, 'swift'))
display(df.style.hide())

print('All Virtual Persons Buggy Javascript oref Simulation Results')
df = pd.DataFrame.from_dict(age_group_results(all_users, all_users_display, 'jsbug'))
display(df.style.hide())

All Virtual Persons Swift oref Simulation Results

All Virtual Persons Buggy Javascript oref Simulation Results

## Parkes Error Analysis

In [9]:
from ParkesErrorGrid.parkes_error import ParkesError

In [10]:
def user_parkes_grid(user, user_display=None, gen_plot=False):

    if gen_plot and not user_display:
        raise Exception(f"Must give value for user_display if gen_plot=True.")
    
    ref_trace = pd.read_csv(f"simglucoseResults/{user}/swift.csv")["CGM"].to_list()
    pred_trace = pd.read_csv(f"simglucoseResults/{user}/jsbug.csv")["CGM"].to_list()
    grid = ParkesError(ref_trace, pred_trace)
    if gen_plot:
        grid.plot(user_display, "Swift Algorithm Glucose", 
                "Original Javascript Algorithm Glucose", size=1, 
                save_fig_path=f"simglucoseResults/{user}/parkes_error.png")
        
    grid_flip = ParkesError(pred_trace, ref_trace)
    if gen_plot:
        grid_flip.plot(user_display, "Original Javascript Algorithm Glucose",
                "Swift Algorithm Glucose", size=1, 
                save_fig_path=f"simglucoseResults/{user}/parkes_error_flipped.png")

    return grid.zone_count(), grid_flip.zone_count()

In [11]:
swift_ref_users = {}
js_ref_users = {}

for user in all_users:
    swift_ref, js_ref = user_parkes_grid(user)
    n = sum(swift_ref.values())
    swift_ref_users[user] = [round(100*count/n, 2) for count in swift_ref.values()]
    js_ref_users[user] = [round(100*count/n, 2) for count in js_ref.values()]

In [12]:
df = pd.DataFrame.from_dict(swift_ref_users, orient='index', columns=['A', 'B', 'C', 'D', 'E'])
display(df)

                    A     B     C    D    E
child001        97.59  2.41  0.00  0.0  0.0
child002        99.98  0.02  0.00  0.0  0.0
child003       100.00  0.00  0.00  0.0  0.0
child004        91.97  7.79  0.25  0.0  0.0
child005        99.83  0.17  0.00  0.0  0.0
child006       100.00  0.00  0.00  0.0  0.0
child007       100.00  0.00  0.00  0.0  0.0
child008        99.88  0.12  0.00  0.0  0.0
child009        99.43  0.57  0.00  0.0  0.0
child010        99.85  0.15  0.00  0.0  0.0
adolescent001  100.00  0.00  0.00  0.0  0.0
adolescent002  100.00  0.00  0.00  0.0  0.0
adolescent003  100.00  0.00  0.00  0.0  0.0
adolescent004  100.00  0.00  0.00  0.0  0.0
adolescent005  100.00  0.00  0.00  0.0  0.0
adolescent006  100.00  0.00  0.00  0.0  0.0
adolescent007  100.00  0.00  0.00  0.0  0.0
adolescent008  100.00  0.00  0.00  0.0  0.0
adolescent009  100.00  0.00  0.00  0.0  0.0
adolescent010  100.00  0.00  0.00  0.0  0.0
adult001       100.00  0.00  0.00  0.0  0.0
adult002       100.00  0.00  0.00  0.0  0.0
adult003       100.00  0.00  0.00  0.0  0.0
adult004       100.00  0.00  0.00  0.0  0.0
adult005       100.00  0.00  0.00  0.0  0.0
adult006       100.00  0.00  0.00  0.0  0.0
adult007        99.73  0.27  0.00  0.0  0.0
adult008       100.00  0.00  0.00  0.0  0.0
adult009       100.00  0.00  0.00  0.0  0.0
adult010       100.00  0.00  0.00  0.0  0.0

In [13]:
df = pd.DataFrame.from_dict(js_ref_users, orient='index', columns=['A', 'B', 'C', 'D', 'E'])
display(df)

                    A     B    C    D    E
child001        98.86  1.14  0.0  0.0  0.0
child002       100.00  0.00  0.0  0.0  0.0
child003        99.88  0.12  0.0  0.0  0.0
child004        92.64  7.36  0.0  0.0  0.0
child005       100.00  0.00  0.0  0.0  0.0
child006       100.00  0.00  0.0  0.0  0.0
child007       100.00  0.00  0.0  0.0  0.0
child008        99.78  0.22  0.0  0.0  0.0
child009        99.50  0.50  0.0  0.0  0.0
child010       100.00  0.00  0.0  0.0  0.0
adolescent001  100.00  0.00  0.0  0.0  0.0
adolescent002  100.00  0.00  0.0  0.0  0.0
adolescent003  100.00  0.00  0.0  0.0  0.0
adolescent004  100.00  0.00  0.0  0.0  0.0
adolescent005  100.00  0.00  0.0  0.0  0.0
adolescent006  100.00  0.00  0.0  0.0  0.0
adolescent007  100.00  0.00  0.0  0.0  0.0
adolescent008  100.00  0.00  0.0  0.0  0.0
adolescent009  100.00  0.00  0.0  0.0  0.0
adolescent010  100.00  0.00  0.0  0.0  0.0
adult001       100.00  0.00  0.0  0.0  0.0
adult002       100.00  0.00  0.0  0.0  0.0
adult003       100.00  0.00  0.0  0.0  0.0
adult004       100.00  0.00  0.0  0.0  0.0
adult005       100.00  0.00  0.0  0.0  0.0
adult006       100.00  0.00  0.0  0.0  0.0
adult007       100.00  0.00  0.0  0.0  0.0
adult008       100.00  0.00  0.0  0.0  0.0
adult009       100.00  0.00  0.0  0.0  0.0
adult010       100.00  0.00  0.0  0.0  0.0